version: '3'
services:
  app:
    container_name: music_room_app
    image: music_room
    depends_on:
      - db
    restart: on-failure
    ports:
      - "9443:9443"
      - "8666:8666"
  db:
    container_name: music_room_db
    image: postgres:11.3
    environment:
      POSTGRES_DB: music_room
    volumes:
      - $HOME/docker/volumes/music_room_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5